### ISSUE TITLE
Confusing error message if CPI can't find GCP creds

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/bosh-google-cpi-release#121]
I've seen a couple users (myself included) hit the following error:

```
creating stemcell (bosh-google-kvm-ubuntu-trusty-go_agent 3312):
  CPI 'create_stemcell' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"Creating stemcell: Creating Google Image from URL: Failed to create Google Image: Post https://www.googleapis.com/compute/v1/projects/cf-bosh-concourse/global/images?alt=json: Get http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token: dial tcp 169.254.169.254:80: i/o timeout","ok_to_retry":false}
```

This error means the CPI can't locate your GCP creds. The lookup process for creds is:
- Looks for `instance_groups.bosh.properties.google.json_key` in the Director manifest
- Looks on disk for files created as part of a previous `gcloud auth login` call
- Tries to hit the GCP metadata server at `169.254.169.254`

So if the Operator has not specified `json_key` in their manifest, and has not run `gcloud auth login` at some point, and is running the deployment from outside a GCP instance, then they will get the above error message. It would be nice to display a better error message, but in the meantime maybe search engines will route people here if they hit this error :)

**Comment by alex-slynko** [comment]
We have got a slightly different error, but still a similar one:
`CmdError{"type":"Bosh::Clouds::CloudError","message":"Creating stemcell: Creating Google Storage Bucket: ...`

**Comment by jenspinney** [comment]
Yeah, we just ran into this error as well. Thanks @ljfranklin from keeping us from hitting our heads against the wall for too long! It would definitely be nice to have a more clear error message in this case.

**Comment by johnsonj** [comment]
We should validate the credentials earlier on so we can provide a clear permissions error.
