### ISSUE TITLE
Remove registry configuration from CPI since it uses updatable metadata

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/bosh-google-cpi-release#127]
- https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blob/master/jobs/google_cpi/spec#L97
- prolly some go code that can also we removed

**Comment by johnsonj** [comment]
I think this is worth keeping as long as the BOSH registry is sticking around. It is functional as far as I can tell. Metadata would be my preferred way but I don't think we gain anything by removing the support.

**Comment by cppforlife** [comment]
> I think this is worth keeping as long as the BOSH registry is sticking
around.

we are actually in the process of removing registry support from the
director, though it's a long piece of work.

> Metadata would be my preferred way but I don't think we gain anything by
removing the support.

we dont want anyone accidentally configuring it (run into this twice so
far, may be old manifests were found by users). also just extra code.

**Comment by johnsonj** [comment]
Upstream removal is a good reason.
