### ISSUE TITLE
Async VM delete

### ISSUE THREAD

**Issue by vito** [cloudfoundry/bosh-google-cpi-release#191]
On Concourse we have a test suite called [`TopGun`](https://github.com/concourse/topgun) which is an operator-level test suite. It does BOSH `deploy`s and `delete-deployments` before/after every test. We've found that on GCP, deleting a VM takes many times longer than creating them, and this causes the tests to take much longer to finish, especially as we add more tests.

Would it be possible to add a config so that VM deletion is asynchronous?

**Comment by johnsonj** [comment]
I wouldn't mind a feature like that myself. We give VMs unique names on creation so there isn't a risk of name collision on delete/create. 

Is there a feature like this in other CPIs or are other clouds faster at deleting?

**Comment by vito** [comment]
The AWS CPI is faster at deleting, possibly in some part thanks to the IaaS. The tricky part is actually around the IPs - depending on the network config (mainly whether it's `manual`), BOSH will have to wait for the IP to be released by the IaaS before continuing to ensure it doesn't try to use the same IP immediately.

Using a dynamic network helps (I figure that makes the IaaS choose), but even that seems to be not enough:

I found [this magic var](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blob/e84f61b28ec0a98cff7f1628f7d930f598f939fc/src/bosh-google-cpi/google/instance_service/google_instance_service_delete.go#L11) and hacked it in to our director, and while it did greatly help with performance, I just ran in to the following failure even with a dynamic network:

```
Task 141214

13:51:18 | Preparing deployment: Preparing deployment (00:00:01)
13:51:24 | Preparing package compilation: Finding packages to compile (00:00:00)
13:51:24 | Compiling packages: tracker_resource/eed1e1b52a21132e6d82e82701a92ed045e8cb5f
13:51:24 | Compiling packages: github_release_resource/811dbdb6d4319ec5511dcdccd669c7a2c768d7f3
13:51:24 | Compiling packages: git_resource/b5f8f4e2046798e6d357c9df52ec3c28b132a1f4 (00:01:47)
13:53:11 | Compiling packages: docker_image_resource/5319a2ac65ad46fa0cebe06b2113656f6225c38e
13:53:19 | Compiling packages: tracker_resource/eed1e1b52a21132e6d82e82701a92ed045e8cb5f (00:01:55)
13:53:19 | Compiling packages: worker_version/bc790e9ddcfcaf3f3f6dca527151c94209c35843
13:53:19 | Compiling packages: github_release_resource/811dbdb6d4319ec5511dcdccd669c7a2c768d7f3 (00:01:55)
13:53:19 | Compiling packages: concourse_version/40c8c91e12af4175ec8abd813c7ad1d71a180f53
13:53:33 | Compiling packages: worker_version/bc790e9ddcfcaf3f3f6dca527151c94209c35843 (00:00:14)
13:53:33 | Compiling packages: golang/57b32e5a561e23701e9017d0abed6b9e925ec2ff
13:53:33 | Compiling packages: concourse_version/40c8c91e12af4175ec8abd813c7ad1d71a180f53 (00:00:14)
13:53:34 | Compiling packages: docker_image_resource/5319a2ac65ad46fa0cebe06b2113656f6225c38e (00:00:23)
13:54:07 | Compiling packages: golang/57b32e5a561e23701e9017d0abed6b9e925ec2ff (00:00:34)
13:54:07 | Compiling packages: baggageclaim/160bf4cb540805dcd306a726ece308f634172c17
13:54:07 | Compiling packages: groundcrew/7b24f2447816b7d0df9dbebaf3b0cebbef3d9369
13:54:07 | Compiling packages: resource_discovery/297653dce203481808b5e23b757f5aedd255b4d0 (00:00:22)
13:54:29 | Compiling packages: tsa/ca85d36d2ffd6a6cca955f098cea272fbd934dfa
13:54:31 | Compiling packages: baggageclaim/160bf4cb540805dcd306a726ece308f634172c17 (00:00:24)
13:54:31 | Compiling packages: fly/95be71345df0e3810f26c15873d04e01adba294f
13:54:31 | Compiling packages: groundcrew/7b24f2447816b7d0df9dbebaf3b0cebbef3d9369 (00:00:24)
13:54:31 | Compiling packages: atc/5b710d25bb6a22e6060fa31fc37479eafa514dbc
13:54:51 | Compiling packages: fly/95be71345df0e3810f26c15873d04e01adba294f (00:00:20)
13:54:51 | Compiling packages: blackbox/15084c55a9b3d419d9f53fb46432e8d461e7d1df
13:54:55 | Compiling packages: tsa/ca85d36d2ffd6a6cca955f098cea272fbd934dfa (00:00:26)
13:55:12 | Compiling packages: blackbox/15084c55a9b3d419d9f53fb46432e8d461e7d1df (00:00:21)
13:55:13 | Compiling packages: atc/5b710d25bb6a22e6060fa31fc37479eafa514dbc (00:00:42)
13:55:14 | Updating instance web: web/1b0f70c0-d9db-4b45-b274-7b4648d4dc94 (0) (canary)
13:55:15 | Updating instance worker: worker/1127d957-4722-45d9-b014-b6d609296a63 (0) (canary) (00:04:08)
            L Error: CPI error 'Bosh::Clouds::VMCreationFailed' with message 'VM failed to create: Google Operation 'operation-1496239115633-550d250fc8168-803a85fc-691a5a2e' finished with an error: IP '10.1.0.11' is already being used by another resource.
' in 'create_vm' CPI method
14:00:13 | Updating instance web: web/1b0f70c0-d9db-4b45-b274-7b4648d4dc94 (0) (canary) (00:04:59)
14:00:13 | Updating instance web: web/ab2ad710-ad61-4c75-8bae-2b1c72e10a28 (2) (00:04:49)
14:05:02 | Updating instance web: web/df637d35-76de-4fe0-8eba-d8712e3f0250 (1) (00:04:59)

14:10:01 | Error: CPI error 'Bosh::Clouds::VMCreationFailed' with message 'VM failed to create: Google Operation 'operation-1496239115633-550d250fc8168-803a85fc-691a5a2e' finished with an error: IP '10.1.0.11' is already being used by another resource.
' in 'create_vm' CPI method

Started  Wed May 31 13:51:18 UTC 2017
Finished Wed May 31 14:10:01 UTC 2017
Duration 00:18:43

Task 141214 error

Updating deployment:
  Expected task '141214' to succeed but was state is 'error'

Exit code 1
```

Maybe there's some part of dynamic networking I don't understand. Maybe it makes a call to the IaaS to pick an IP, without reserving it, and then creates a VM, so with a parallel deploy there's still a chance of collision? No idea.

Strangely I've only seen this one time. TopGun has never run in to it, and has been humming along nice and quick. It initially failed all the time with manual networks, but after switching to dynamic, everything was OK.

**Comment by johnsonj** [comment]
AFAIK the IaaS gives us an IP back, the IP property should be blank for a dynamic network ([here](https://sourcegraph.com/github.com/cloudfoundry-incubator/bosh-google-cpi-release@5650f9350dd577951c3810574cc69c9a5a636ec3/-/blob/src/bosh-google-cpi/google/instance_service/google_instance_service_create.go?utm_source=chrome-extension#L181-182)). Is it possible you had a stale cloud config locally?

In general I think we want to keep this as a test only 'magic' feature as it is today given the possible caveats but I'll defer to @evandbrown on that when he's back. 

If this is looking good from your end then please close this issue.

**Comment by cppforlife** [comment]
@johnsonj technically if director is recreating instance (instead of creating _new_ instance) it will provide ip even for dynamic network (more of a hint to the cpi). hopefully cpi doesnt try to assign given ip for the dynamic networks.

**Comment by dpb587-pivotal** [comment]
FYI, BOSH fixed the Google stemcell in ubuntu-xenial/v87+ such that deletions should be much faster. Historically the stemcell ignored the ACPI shutdown and Google gives a ~2m grace period for the OS to respect the signal before powering off. Details in [story](https://www.pivotaltracker.com/n/projects/956238/stories/157450843).

Nowadays on Xenial, Google VM deletion should be fairly standard, ~30s.
