### ISSUE TITLE
[Feature] Real names for vms

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh-google-cpi-release#217]
Currently, the vms are named as `vm-UUID`, which is very inconvenient for finding a specific VM in a list of things. See this screenshot: 
<img width="430" alt="screen shot 2017-07-28 at 10 33 39" src="https://user-images.githubusercontent.com/2256887/28709439-9fba64fa-7380-11e7-83d6-255b4596fee5.png">

Other cpis, such as AWS and OpenStack have real names. The `set_vm_metadata` method even gets `name` as metadata argument, see https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/blob/643f19e2e0b4ce11d5ac5ed903bdc08f2f3f7238/src/bosh_openstack_cpi/lib/cloud/openstack/cloud.rb#L601

I'm not very familiar with how GCP deals with VM names, but could this be added? Thanks!

**Comment by johnsonj** [comment]
We don't have a friendly name sort of field that allows us to update the name of a VM after creation time (when `set_vm_metadata` happens). 

We will need more information from BOSH in the `create_vm` call to support this, but I like the idea. Let me see can be done.

**Comment by mrdavidlaing** [comment]
Related - https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/issues/150

**Comment by voelzmo** [comment]
See above: we're thinking about how to provide the necessary metadata for naming during `create_vm` and `create_volume` calls. My understanding is that this should make it possible to have nicer VM names on GCP. @evandbrown does this sound correct?

**Comment by evandbrown** [comment]
@voelzmo I've got a new engineer spinning up on the CPI tomorrow. I'll put this in his backlog.

**Comment by voelzmo** [comment]
Hold your horses, @evandbrown ;) I appreciate the enthusiasm, but the metadata isn't available yet during `create_vm`. We're about to make this happen with https://github.com/cloudfoundry/bosh-notes/pull/48 though. Just wanted to confirm that this would be possible in the CPI then as I'm not much aware of the GCP APIs.
