### ISSUE TITLE
Default Quota not enough for all compilation workers

### ISSUE THREAD

**Issue by cxhercules** [cloudfoundry/bosh-google-cpi-release#227]
You make mention in [README.md](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blob/master/docs/cloudfoundry/README.md), that "CF deployment is small enough to fit into a default project resource quota, but I seems not to be the case. Persistent disk default quota per zone is 500GB. I even raised mine to 1000GB and was still getting this error:

```
04:47:43 | Compiling packages: uaa/b8983f67d06dc9a9f29c2d8493443a7f5aba5f5a (00:02:05)
            L Error: CPI error 'Bosh::Clouds::VMCreationFailed' with message 'VM failed to create: Google Operation 'operation-1504846039123-558a6459a8439-a40185b9-c004b3bd' finished with an error: Quota 'SSD_TOTAL_GB' exceeded.  Limit: 1000.0
' in 'create_vm' CPI method
04:47:50 | Compiling packages: busybox/1593c41beb57c12d7f2b82dff61b47d4d119913d (00:02:12)
            L Error: CPI error 'Bosh::Clouds::VMCreationFailed' with message 'VM failed to create: Google Operation 'operation-1504846047154-558a646150f50-32f3843a-94d8f37c' finished with an error: Quota 'SSD_TOTAL_GB' exceeded.  Limit: 1000.0
' in 'create_vm' CPI method
04:47:54 | Compiling packages: binary-buildpack/be1e800f84b0048babd1d501b2b0e75abc776839 (00:00:31)
```

I finally took a look at manifest and noticed there were 12 compilation workers with 100 gb disk each. Although they go away, if they all come up about same time they consume all the quota. I lowered number of workers at cost of taking a bit longer to spin up. 

https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blob/master/docs/cloudfoundry/manifest.yml.erb#L93-L104
```
compilation:
  workers: 12
  network: compilation
  reuse_compilation_vms: true
  cloud_properties:
    zone: <%= google_zone_compilation%>
    region: <%= google_region_compilation%>
    machine_type: n1-standard-2
    root_disk_size_gb: 100
    root_disk_type: pd-ssd
    preemptible: true
    service_account: <%= cf_service_account%>
```

**Comment by johnsonj** [comment]
Quota is a moving target I think. I bet we could significantly cut down on disk size (10-15GB?) for these VMs.

**Comment by cxhercules** [comment]
I ran with with one compilation worker, it timed out first time, ran again and succeeded. I think that if we were to make use of other AZ then at least two could run, and if we lowered to 50 gig instead of 100 gig then 4 vm's could run.

**Comment by johnsonj** [comment]
We currently use preemptable VMs for compilation which means timeouts are somewhat expected. It's a nice demonstration of their usage but not necessarily a great getting started experience.

I'm not going to spend any time fixing the current manifest because we really need to adopt cf-deployment (see #158) now that v1.0 has been released. This will likely significantly alter how we deploy OSS CF in these docs. If you're interested in tweaking our current manifest it's much appreciated.
