### ISSUE TITLE
Conflict with subnets created by default VPC creation 

### ISSUE THREAD

**Issue by jasonbisson** [cloudfoundry/bosh-google-cpi-release#262]
The concourse VPC creation adds all the default subnets which eventually collides with the creation of concourse-public-subnet-1 and 2.

Here are the  terraform error messages:
Error 400: Invalid value for field 'resource.ipCidrRange': '10.160.0.0/16'. Extended subnetworks in auto subnet mode networks cannot overlap with 10.128.0.0/9

Error 400: Invalid value for field 'resource.ipCidrRange': '10.150.0.0/16'. Extended subnetworks in auto subnet mode networks cannot overlap with 10.128.0.0/9., invalid

To avoid the auto creation of subnets setting auto_create_subnetworks to false might help.

auto_create_subnetworks = false

**Comment by dfoleypivotal** [comment]
I just received this error.  Looks like this issue has never been addressed
