### ISSUE TITLE
bosh deploy fails with postgresql not found

### ISSUE THREAD

**Issue by rjain-pivotal** [cloudfoundry/bosh-google-cpi-release#267]
Deploying
---------
Are you sure you want to deploy? (type 'yes' to continue): yes

Director task 5
  Started preparing deployment > Preparing deployment. Failed: Job 'postgresql' not found in Template table (00:00:00)

Error 100: Job 'postgresql' not found in Template table

Task 5 error

**Comment by evandbrown** [comment]
Hi Rajesh,

Is this happening when deploying a new director (`bosh create-env`) or when deploying a different release to an existing director?

**Comment by cppforlife** [comment]
@evandbrown judging by `Director task 5` i assume it's `bosh deploy ...`.

@rjain-pivotal this doesnt sound like a google cpi problem. if you are deploying some release make sure that manifest references jobs that are available in your release (postgresql job in this case).

**Comment by cppforlife** [comment]
i also notice that this repo contains outdated concoutse manifests (that includes `postgresql`). if you are using that i would encourage you to look at https://github.com/concourse/concourse-bosh-deployment (official concourse+bosh deployment mechanism).

@evandbrown would be nice to kill cf, concourse, bosh docs out of this repo.
