### ISSUE TITLE
Bosh create-env network project_id empty

### ISSUE THREAD

**Issue by daviddob** [cloudfoundry/bosh-google-cpi-release#269]
When deploying bosh via create-env with the google-cpi the following message is present in debug logs and some errors.

```
[GoogleSubnetworkService] 2018/04/27 13:54:07 DEBUG - Finding Google Subnetwork 'test' in region 'us-east4' in project ''
```

The project_id is empty though it is specified in the manifest and even when the deployment is successful this message still has the project_id as empty.

**Comment by evandbrown** [comment]
Hi @daviddob, any chance you could link to the manifest that's causing these problems? Also, do you know the version of the CPI you're using?

**Comment by daviddob** [comment]
Hi Evan, 

I am using the manifest from bosh-deployment [bosh.yml](https://github.com/cloudfoundry/bosh-deployment/blob/master/bosh.yml)

I believe it is using 27.0.0 [cpi.yml](https://github.com/cloudfoundry/bosh-deployment/blob/master/gcp/cpi.yml)

**Comment by cppforlife** [comment]
@daviddob mind throwing in command you are executing with all the `-o` calls.

**Comment by daviddob** [comment]
```
export BOSH_LOG_LEVEL=debug
bosh create-env bosh-deployment/bosh.yml \
    --state=state.json \
    --vars-store=creds.yml \
    -o bosh-deployment/gcp/cpi.yml \
    -v director_name=bosh \
    -v internal_cidr=10.200.0.0/26 \
    -v internal_gw=10.200.0.1 \
    -v internal_ip=10.200.0.6 \
    --var-file gcp_credentials_json=/path/to/service-acct.key.json \
    -v project_id=test \
    -v zone=us-east4-a \
    -v tags=[internal] \
    -v network=test \
    -v subnetwork=test
```
