### ISSUE TITLE
support multi-cpi configuration

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/bosh-google-cpi-release#270]
some quick hack was done on: https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/tree/wip-cpi-config-support

this allows to use cpi-config (one use case is to have multiple projects be managed by the same director).

**Comment by alwaysastudent** [comment]
It would be useful if the same director can manage multiple GCP projects.

**Comment by evandbrown** [comment]
@cppforlife would like to get this from wip to merged. Would you mind opening a PR for this branch so we can review there?

One other question: is there a practical maximum for the number of CPIs a director will support? 10s? 100s?

**Comment by katter** [comment]
I'd like to second what @alwaysastudent said. Being able to deploy into multiple GCP Projects in conjunction with isolation segments would help us quite a bit in figuring out who generates what costs etc.
