### ISSUE TITLE
Automatic restart option

### ISSUE THREAD

**Issue by dmitry-bakaleinik-sap** [cloudfoundry/bosh-google-cpi-release#273]
Hello,

According to the documentation (https://bosh.io/docs/google-cpi/), the `automatic_restart` option is false by default. If I correctly understand the behavior, in case of non-user restart the VM should remain in the stopped state and then BOSH can detect it as unreachable VM and run a resurrection process.

But I can't see that this option is applied to VMs when I inspect them in google console, the "Automatic Restart" parameter is set as "On (recommended)". 

Also, I don't see any change also if I explicitly set automatic_restart to false in cloud configuration for the VM.

**Comment by evandbrown** [comment]
To clarify, you're seeing "Automatic restart" always selected even when you set it to `false` in `cloud_properties`? If so, I'll take a look tomorrow. 

Thanks!

**Comment by ninja-at-work** [comment]
Yes, even with explicitly set "automatic_restart: false" property the VM is created with "Automatic restart	- On (recommended)" settings.
