### ISSUE TITLE
cpi logs in `/var/vcap/sys/log/google_cpi` instead of bosh task log

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh-google-cpi-release#278]
I was confused to find detailed CPI logs in `/var/vcap/sys/log/google_cpi` instead of `bosh task <ID> --debug` or `bosh task <ID> --cpi`. This seems to be what other CPIs I've been using and implementing do. This makes it hard to correlate CPI calls to the specific tasks, especially given that the CPI binary is executed in parallel multiple times.

**Comment by voelzmo** [comment]
Corresponding section in the API description between Director and CPI: https://bosh.io/docs/cpi-api-v1-rpc/#response

**Comment by voelzmo** [comment]
@craigatgoogle any updates on this?

**Comment by craigatgoogle** [comment]
Hi Marco. Thank you for your patience on this issue and the others. We're currently in the process of ramping up some new team members who will be taking ownership of this project, which is the cause for the delay. I'm re-assigning these issues back to @evandbrown as he is coordinating the transition.

**Comment by evandbrown** [comment]
Hey @voelzmo, thanks for pointing this out. I'll take this one; should have something tomorrow.

**Comment by voelzmo** [comment]
Thanks for the merge, @evandbrown. I didn't see any sanitation being done for the logs, does this means that you're now dumping credentials and other sensitive information directly into the task's debug log? You can check how other CPIs are doing this by e.g. taking a hint from the openstack cpi: https://github.com/cloudfoundry/bosh-openstack-cpi-release/blob/master/src/bosh_openstack_cpi/lib/cloud/openstack/excon_logging_instrumentor.rb#L29-L36

This heavily depends on the place and kind of credentials for the IaaS, though.
