### ISSUE TITLE
Attach disk returns an error if disk is already attached

### ISSUE THREAD

**Issue by BeckerMax** [cloudfoundry/bosh-google-cpi-release#280]
The CPI action [AttachDisk](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blob/426cbc85adee9e23c36b8afcbe874148f9bcfa5c/src/bosh-google-cpi/action/attach_disk.go#L31) seems to not check whether the disk is already attached.

This caused the following error for us when we ran `cck` to repair a failing deployment where the VM crashes after migrating a disk.

```
Error: Error resolving problem '60': CPI error 'Bosh::Clouds::CloudError' with message 'Attaching disk 'disk-abc' to vm 'vm-123': Failed to attach Google Disk 'disk-abc' to Google Instance 'vm-123': Google Operation 'operation-456' finished with an error: The disk resource '.../disks/disk-abc' is already being used by .../instances/vm-123'' in 'attach_disk' CPI method (CPI request ID: 'cpi-123')
```

It should be reproducible by manually attaching a disk via the gcp-console and then running `bosh attach-disk` on the already attached disk.

**Comment by voelzmo** [comment]
@craigatgoogle: any updates on this?

**Comment by evandbrown** [comment]
Ack. Working on a fix.
