### ISSUE TITLE
Add labels to images so that orphaned stemcells can be deleted by their environment/deployment name

### ISSUE THREAD

**Issue by genevieve** [cloudfoundry/bosh-google-cpi-release#287]
This release creates images with the name `stemcell-GUID`. When stemcells are orphaned, they are harder to delete because there is no way to determine which environment it belongs to from the resource alone. 

In github.com/genevieve/leftovers, we help clean up infrastructure orphaned by terraform or bosh. It accepts a filter so that it only deletes resources belonging to environments you know are safe to delete. The filter you provide is most likely your environment/deployment name. The safest way to delete stemcells is to have labels on them, otherwise, we could easily delete stemcells that are in use by running environments in gcp.

Here's an issue related to leftover stemcells: https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/issues/162

Here's the corresponding issue in leftovers: https://github.com/genevieve/leftovers/issues/66

cc @evandbrown

**Comment by DanielJonesEB** [comment]
We're also being bitten by this in Concourse-Up - we can't clean up orphaned images, because we don't know if they belong to failed system tests or currently-running ones.

**Comment by evandbrown** [comment]
Thanks for the report and subsequent bump. Once @tysen accepts the invite to collab on this repo, I'll add him as assignee and we'll get this knocked out.

**Comment by voelzmo** [comment]
@genevieve @DanielJonesEB just for my understanding: which way are you using/wanting for cleaning up stemcells? From your above descriptions I assume you're not using `bosh clean-up` on a director to get rid of unused artifacts? Or is this about the stemcell which was used to deploy something via `bosh create-env`?

**Comment by genevieve** [comment]
@voelzmo The stemcells I am referring to are via `bosh create-env`.

**Comment by genevieve** [comment]
Hey @tysen! What's the status on this issue? I see a corresponding closed issue about providing information during stemcell creation but no associated commits. Is the next step to use that information in the naming of the stemcell?

**Comment by tysen** [comment]
I'm no longer able to help on this project but @josephlewis42 or @mattysweeps might be able to.

**Comment by genevieve** [comment]
Hey @josephlewis42 @mattysweeps! Have you had a chance to look into this issue?
