### ISSUE TITLE
Network Lifecycle Management

### ISSUE THREAD

**Issue by frodenas** [cloudfoundry/bosh-google-cpi-release#290]
BOSH [v268.0.1](https://github.com/cloudfoundry/bosh/releases/tag/v268.0.1) introduces beta functionality of [network lifecycle management](https://docs.google.com/document/d/1akr17Iep99fCYNqZQv9uoxar7qF04U40O6cYoAsg3lA/edit). Can we add support for this at the Google CPI?

**Comment by tomgpoole** [comment]
+1
