### ISSUE TITLE
create-env: certificates are only valid for x.x.x.6

### ISSUE THREAD

**Issue by poy** [cloudfoundry/bosh-google-cpi-release#297]
When using `bosh create-env --environment=10.128.0.7`, I would expect the generated certificates to be for `10.128.0.6`, however I get the following error:

```
Deploying:
  Creating instance 'bosh/0':
    Waiting until instance is ready:
      Post https://mbus:<redacted>@10.128.0.7:6868/agent: x509: certificate is valid for 10.128.0.6, not 10.128.0.7
Exit code 1
```

**Comment by evandbrown** [comment]
Hey @poy, are you using[ these docs](https://github.com/cloudfoundry/bosh-google-cpi-release/tree/master/docs/bosh) to launch? If so, looks like we need to update them.
