### ISSUE TITLE
Be able to BOSH deploy something when a GCP zone is out of resources

### ISSUE THREAD

**Issue by mjj209** [cloudfoundry/bosh-google-cpi-release#304]
**The Problem**

The problem is that GCP resources are finite, and zones will occasionally run out of resources. This issue presents itself to a BOSH user via the message:

`The zone 'projects/********/zones/us-central1-f' does not have enough resources available to fulfill the request.`

This causes the BOSH deploy to fail.

The error message details that the user should try another zone, or wait. There is no visibility into the 'right' zone to use, as the only insight into the problem stated above is to try and create a VM. There is an open bug tracker here: https://issuetracker.google.com/issues/72811715

There also isn't an indication as to when the problem will clear up, as one zone going down on the GCP platform does not impact any SLAs, given other zones are available inside a region. So nothing is posted to the public GCP Status pages.

**A modest proposal for a solution**

The CPI could automatically retry to create the VM on a different zone so that the deploy can be successful. There is a corresponding issue on the BOSH repo, as BOSH potentially could implement the same logic.

**Comment by davidjahn** [comment]
We are running into this issue extremely often (multiple times per week). The CPI becomes unusable for some time, usually several hours.

It would be nice to gracefully choose a different AZ, if this is possible in the CPI/Bosh interaction.
