### ISSUE TITLE
Flaky communication via CPI

### ISSUE THREAD

**Issue by waciuma4pivotal** [cloudfoundry/bosh-google-cpi-release#316]
We're using version 29.0.1 of the CPI and saw the error below. Wonder if increased retries may improve behavior.

```Error: CPI error 'Bosh::Clouds::CloudError' with message 'Attaching disk 'disk-<ID>' to vm 'vm-<ID>': Failed to find Google Disk 'disk-<ID>': Get https://www.googleapis.com/compute/v1/projects/cf-toolsmiths-private-pool-05/aggregated/disks?alt=json&filter=name+eq+.%2Adisk-<ID>: oauth2: cannot fetch token: Post https://oauth2.googleapis.com/token: net/http: TLS handshake timeout' in 'attach_disk' CPI method (CPI request ID: 'cpi-816131')```

**Comment by voelzmo** [comment]
This might be related to https://github.com/cloudfoundry/bosh-google-cpi-release/issues/279
