### ISSUE TITLE
New bosh google cpi release

### ISSUE THREAD

**Issue by dimitdb** [cloudfoundry/bosh-google-cpi-release#331]
Hi,

This is not really an issue, but a question to the community.

I'd like to ask if there is a release schedule and when can we expect the next release? If there is no schedule, would it be possible to get a new release, that includes my recent [changes](https://github.com/cloudfoundry/bosh-google-cpi-release/pull/329)?

Thanks,
Regards

**Comment by friegger** [comment]
It was discussed in the last Foundational Infrastructure WG Meeting and @rkoster will cut a release soon.

**Comment by dimitdb** [comment]
Thanks, closing the issue.

**Comment by rkoster** [comment]
Yes there is a story in our backlog: https://www.pivotaltracker.com/story/show/181401601 [private]
