### ISSUE TITLE
Bosh director self snapshots are not being triggered

### ISSUE THREAD

**Issue by l-dimitrov** [cloudfoundry/bosh-google-cpi-release#333]
### Versions (*please add them if you have more releases for this issue*)
CPI      Version: 42.0.0
BOSH     Version: 272.2.0

### Stemcell
Version: 1.79
Distro:
  - [x] Ubuntu
  - [ ] CentOS
- Location: (all locations)

### Issue Details
Hi Team,
We have the following scenario for AuditLogService. We are missing self snapshots for the Bosh director on all providers (Ali, GCP, Azure) beside AWS where the following is working fine:
...
enable_snapshots: true
self_snapshot_schedule: 0 1 * * * UTC
I see the snapshot jobs queued in the log:
cat scheduler.stdout.log | grep -i "SnapshotSelf"
I, [2022-03-08T15:01:14.575512 #6](https://jtrack.wdf.sap.corp/browse/NGPBUG-181697#6) [] INFO – Director: added scheduled job 'Bosh::Director::Jobs::SnapshotSelf' with interval '0 1 * * * UTC'
I, [2022-03-09T01:00:00.113901 #6](https://jtrack.wdf.sap.corp/browse/NGPBUG-181697#6) [] INFO – Director: enqueueing 'SnapshotSelf'
I, [2022-03-10T01:00:00.306874 #6](https://jtrack.wdf.sap.corp/browse/NGPBUG-181697#6) [] INFO – Director: enqueueing 'SnapshotSelf'
I, [2022-03-11T01:00:00.058503 #6](https://jtrack.wdf.sap.corp/browse/NGPBUG-181697#6) [] INFO – Director: enqueueing 'SnapshotSelf'
I, [2022-03-12T01:00:00.167865 #6](https://jtrack.wdf.sap.corp/browse/NGPBUG-181697#6) [] INFO – Director: enqueueing 'SnapshotSelf'
I, [2022-03-13T01:00:00.268429 #6](https://jtrack.wdf.sap.corp/browse/NGPBUG-181697#6) [] INFO – Director: enqueueing 'SnapshotSelf'
I, [2022-03-14T01:00:00.211582 #6](https://jtrack.wdf.sap.corp/browse/NGPBUG-181697#6) [] INFO – Director: enqueueing 'SnapshotSelf'
I, [2022-03-15T01:00:00.062717 #6](https://jtrack.wdf.sap.corp/browse/NGPBUG-181697#6) [] INFO – Director: enqueueing 'SnapshotSelf'
I, [2022-03-16T01:00:00.182310 #6](https://jtrack.wdf.sap.corp/browse/NGPBUG-181697#6) [] INFO – Director: enqueueing 'SnapshotSelf'
I, [2022-03-17T01:00:00.109313 #6](https://jtrack.wdf.sap.corp/browse/NGPBUG-181697#6) [] INFO – Director: enqueueing 'SnapshotSelf'
however no snapshots created for all but AWS provides.Any thoughts on why this might be happening? Other VMs are being backed up and the issue is only to bosh director selfsnapshot feature. 
Thanks and regards!

**Comment by beyhan** [comment]
What other logs in that direction can you find. E.g. do you see any of the following logs:
* https://github.com/cloudfoundry/bosh/blob/da56d19e30234239582ecfdd6a2da682631f6832/src/bosh-director/lib/bosh/director/jobs/snapshot_self.rb#L40 
* https://github.com/cloudfoundry/bosh/blob/da56d19e30234239582ecfdd6a2da682631f6832/src/bosh-director/lib/cloud/external_cpi.rb#L120
* https://github.com/cloudfoundry/bosh/blob/da56d19e30234239582ecfdd6a2da682631f6832/src/bosh-director/lib/bosh/director/jobs/snapshot_self.rb#L19
* https://github.com/cloudfoundry/bosh/blob/da56d19e30234239582ecfdd6a2da682631f6832/src/bosh-director/lib/bosh/director/jobs/snapshot_self.rb#L38

**Comment by l-dimitrov** [comment]
Hello, 
Thanks for the response.
./var/vcap/store/director/tasks/1835630/debug:21:I, [2022-05-31T01:00:00.346530 #31890] [task:1835630]  INFO -- DirectorJobRunner: CPI does not support disk snapshots; skipping
./var/vcap/store/director/tasks/1853081/debug:21:I, [2022-06-02T01:00:00.320472 #23887] [task:1853081]  INFO -- DirectorJobRunner: CPI does not support disk snapshots; skipping
./var/vcap/store/director/tasks/1845178/debug:21:I, [2022-06-01T01:00:00.242253 #32646] [task:1845178]  INFO -- DirectorJobRunner: CPI does not support disk snapshots; skipping
looks like CPI is the cause,  any advice on which version should we upgrade to sort this? 
CPI current Version: 42.0.0

**Comment by beyhan** [comment]
This operation is not supported in this CPI. So this never worked. This means that this is more a feature request.
