### ISSUE TITLE
Block project-wide SSH keys for bosh-deployed vms

### ISSUE THREAD

**Issue by max-soe** [cloudfoundry/bosh-google-cpi-release#336]
Hi,

Is there already an option to enable the "Block project-wide SSH keys" option for bosh deployed vms?
This feature is an important security feature for us. 

Best regards,
Max

**Comment by vankatamarinov** [comment]
I research it and found that "Block project-wide SSH keys" is [metadata](https://cloud.google.com/compute/docs/connect/restrict-ssh-keys#during-vm-creation) so only setting block-project-ssh-keys=TRUE in metadata for creating a VM is enough.

**Comment by max-soe** [comment]
Thanks for the fast support!
